### ISSUE TITLE
Memory requirements

### ISSUE THREAD

**Issue by isaacngym** [nsg-ethz/synet#1]
How much memory is this supposed to use? Running this on a computer with 8GB RAM:

```./synet.py -i examples/simple.logic -r examples/simple-req.logic -m bgp>debug_201905291451.log
Traceback (most recent call last):
  File "./synet.py", line 56, in <module>
    main()
  File "./synet.py", line 47, in main
    syn.synthesize()
  File "/home/lucky/Dropbox/Term 8/cs-personal/synet/synet/synthesis3.py", line 484, in synthesize
    if solver.check() == z3.sat:
  File "/home/lucky/anaconda3/envs/cs-synet/lib/python2.7/site-packages/z3/z3.py", line 6626, in check
    r = Z3_solver_check_assumptions(self.ctx.ref(), self.solver, num, _assumptions)
  File "/home/lucky/anaconda3/envs/cs-synet/lib/python2.7/site-packages/z3/z3core.py", line 3702, in Z3_solver_check_assumptions
    _elems.Check(a0)
  File "/home/lucky/anaconda3/envs/cs-synet/lib/python2.7/site-packages/z3/z3core.py", line 1372, in Check
    raise self.Exception(self.get_error_message(ctx, err))
z3.z3types.Z3Exception: out of memory
```

The log also seems to indicate that it's stuck in a loop? After initialising the messages become a loop of:

```

SAT, reading inputs...
	Synthesized input SetAdminDist ['False']
	Synthesized input Route ['False']
	Synthesized input nonMinCostAD ['False']
##############################
Synthesizing for box 12 fwd01-0
Feeding desired outputs for fwd01-0...
	Feeding desired output fwd01-0 [ForAll([t0, t1, t2, t3], Route(t0, t1, t2, t3) == False)]
	Feeding desired output fwd01-0 [ForAll([t0, t1, t2], nonMinCostAD(t0, t1, t2) == False)]
	Feeding shortcut INPUT fwd01-0 [ForAll([t0, t1, t2], SetAdminDist(t0, t1, t2) == False)]
Checking SAT for box fwd01-0 ...
!!!!!!!!!!!!!!!!!!!!
UNSAT going back to 13 fwd01-1
##############################
Synthesizing for box 13 fwd01-1
Feeding desired outputs for fwd01-1...
Checking SAT for box fwd01-1 ...
```

[debug_201905291451.log](https://github.com/nsg-ethz/synet/files/3233097/debug_201905291451.log)

Is this an issue of an infinite loop somewhere or my machine having insufficient RAM?

**Comment by ahassany** [comment]
As we described in our [evaluation](https://synet.ethz.ch/files/synet-cav2017.pdf) we ran SyNET on a machine with 128G of RAM. I've not tried with less RAM before.
It's normal for SyNET to try multiple times, this part of the back tracking algorithm described in our paper.

**Comment by isaacngym** [comment]
Apparently I didn't read the evaluation closely enough. Thanks.

re: the backtracking, I expected it to contain different logging messages when it backtracks. Appreciate the clarification.
